name: Python CI and testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Copy the code to test
      uses: actions/checkout@v3
    - name: Set up Python
      used: actions/setup-python@v3
      with: 
        python-version: 3.11
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install pytest
    - name: Testing the code with pytest
      run: cd day3 && pytest
